package com.tuesdayma.middleware.sharding.dal.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table my_order_detail
 */
public class MyOrderDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_order_detail.id
     *
     * @mbg.generated Tue Mar 09 16:30:26 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_order_detail.order_no
     *
     * @mbg.generated Tue Mar 09 16:30:26 CST 2021
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_order_detail.goods_id
     *
     * @mbg.generated Tue Mar 09 16:30:26 CST 2021
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_order_detail.num
     *
     * @mbg.generated Tue Mar 09 16:30:26 CST 2021
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table my_order_detail
     *
     * @mbg.generated Tue Mar 09 16:30:26 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_order_detail.id
     *
     * @return the value of my_order_detail.id
     *
     * @mbg.generated Tue Mar 09 16:30:26 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_order_detail.id
     *
     * @param id the value for my_order_detail.id
     *
     * @mbg.generated Tue Mar 09 16:30:26 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_order_detail.order_no
     *
     * @return the value of my_order_detail.order_no
     *
     * @mbg.generated Tue Mar 09 16:30:26 CST 2021
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_order_detail.order_no
     *
     * @param orderNo the value for my_order_detail.order_no
     *
     * @mbg.generated Tue Mar 09 16:30:26 CST 2021
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_order_detail.goods_id
     *
     * @return the value of my_order_detail.goods_id
     *
     * @mbg.generated Tue Mar 09 16:30:26 CST 2021
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_order_detail.goods_id
     *
     * @param goodsId the value for my_order_detail.goods_id
     *
     * @mbg.generated Tue Mar 09 16:30:26 CST 2021
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_order_detail.num
     *
     * @return the value of my_order_detail.num
     *
     * @mbg.generated Tue Mar 09 16:30:26 CST 2021
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_order_detail.num
     *
     * @param num the value for my_order_detail.num
     *
     * @mbg.generated Tue Mar 09 16:30:26 CST 2021
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order_detail
     *
     * @mbg.generated Tue Mar 09 16:30:26 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderNo=").append(orderNo);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", num=").append(num);
        sb.append("]");
        return sb.toString();
    }
}