package com.tuesdayma.middleware.sharding.dal.mapper;

import com.tuesdayma.middleware.sharding.dal.entity.Goods;
import com.tuesdayma.middleware.sharding.dal.entity.GoodsCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Tue Mar 09 17:05:17 CST 2021
     */
    long countByExample(GoodsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Tue Mar 09 17:05:17 CST 2021
     */
    int deleteByExample(GoodsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Tue Mar 09 17:05:17 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Tue Mar 09 17:05:17 CST 2021
     */
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Tue Mar 09 17:05:17 CST 2021
     */
    int insertSelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Tue Mar 09 17:05:17 CST 2021
     */
    List<Goods> selectByExample(GoodsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Tue Mar 09 17:05:17 CST 2021
     */
    Goods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Tue Mar 09 17:05:17 CST 2021
     */
    int updateByExampleSelective(@Param("record") Goods record, @Param("example") GoodsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Tue Mar 09 17:05:17 CST 2021
     */
    int updateByExample(@Param("record") Goods record, @Param("example") GoodsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Tue Mar 09 17:05:17 CST 2021
     */
    int updateByPrimaryKeySelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Tue Mar 09 17:05:17 CST 2021
     */
    int updateByPrimaryKey(Goods record);
}