package com.tuesdayma.middleware.sharding.dal.mapper;

import com.tuesdayma.middleware.sharding.dal.entity.MyOrderDetail;
import com.tuesdayma.middleware.sharding.dal.entity.MyOrderDetailCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MyOrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order_detail
     *
     * @mbg.generated Tue Mar 09 17:03:49 CST 2021
     */
    long countByExample(MyOrderDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order_detail
     *
     * @mbg.generated Tue Mar 09 17:03:49 CST 2021
     */
    int deleteByExample(MyOrderDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order_detail
     *
     * @mbg.generated Tue Mar 09 17:03:49 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order_detail
     *
     * @mbg.generated Tue Mar 09 17:03:49 CST 2021
     */
    int insert(MyOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order_detail
     *
     * @mbg.generated Tue Mar 09 17:03:49 CST 2021
     */
    int insertSelective(MyOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order_detail
     *
     * @mbg.generated Tue Mar 09 17:03:49 CST 2021
     */
    List<MyOrderDetail> selectByExample(MyOrderDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order_detail
     *
     * @mbg.generated Tue Mar 09 17:03:49 CST 2021
     */
    MyOrderDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order_detail
     *
     * @mbg.generated Tue Mar 09 17:03:49 CST 2021
     */
    int updateByExampleSelective(@Param("record") MyOrderDetail record, @Param("example") MyOrderDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order_detail
     *
     * @mbg.generated Tue Mar 09 17:03:49 CST 2021
     */
    int updateByExample(@Param("record") MyOrderDetail record, @Param("example") MyOrderDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order_detail
     *
     * @mbg.generated Tue Mar 09 17:03:49 CST 2021
     */
    int updateByPrimaryKeySelective(MyOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order_detail
     *
     * @mbg.generated Tue Mar 09 17:03:49 CST 2021
     */
    int updateByPrimaryKey(MyOrderDetail record);
}